# Environment for ipyparaview with jupyterlab
name: ipy_dev
channels:
- conda-forge
- nvidia
- rapidsai
- defaults
dependencies:
- python
- ipython
- pillow
- pip
- numpy
- nodejs
- rapids=0.13 # necessary for the MNIST demo
- pip:
    - ipywidgets
    - jupyter
    - jupyterlab
    - pvgeo # necessary for the MNIST demo
