# Environment for ipyparaview with jupyterlab
name: ipy_dev
channels:
- conda-forge
dependencies:
- python=3.7.4
- ipywidgets
- jupyter
- jupyterlab
- ipython
- pillow
- pip
- pip:
    - python-language-server
